#!/usr/bin/env sh
args=$1
script=$2

file_extension=$(echo $script |awk -F . '{if (NF>1) {print $NF}}')

if [ "$file_extension" = "md" ]
then
    cat $script | awk '{ if (/^```/) { i++; next } if ( i % 2 == 1) { print } }' > $script.out
    $args $script.out
    exit_code=$?
    rm $script.out
else
    $args $script
    exit_code=$?
fi
exit $exit_code
