#!/usr/bin/env sh
args=$1
script=$2


if [ $1 = "--upgrade" ]
then
    sudo wget blaze.oat.sh/blaze -O $(readlink -f $0)
    sudo chmod +x $(readlink -f $0)
    exit 0
fi

file_extension=$(echo $script |awk -F . '{if (NF>1) {print $NF}}')

if [ "$file_extension" = "md" ]
then
    awk '{ if (/^```/) { i++; next } if ( i % 2 == 1) { print } }'< $script > $script.out
    $args $script.out
    exit_code=$?
    rm $script.out
else
    $args $script
    exit_code=$?
fi
exit $exit_code
